# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Global environment variables
env:
    global:
        - DIST=xenial
        # Default beaver image names. May be overriden in specific stages
        - BEAVER_DOCKER_IMG=builder
        - BEAVER_DOCKER_CONTEXT=docker/builder
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

# Do a shallow submodule fetch
before_install: git submodule update --init

# Basic config is inherited from the global scope
jobs:
    templates:
        - &test-matrix
          stage: Test
          after_success: beaver dlang codecov
          script:
              - set -e # Do not continue on failure
              - beaver dlang install
              - beaver dlang make test
        - &package-matrix
          stage: Build and upload packages
          if: tag IS present
          script:
              - set -e # Do not continue on failure
              - beaver dlang install
              - beaver dlang make all
              - beaver dlang make pkg
              - beaver bintray upload -d sociomantic-tsunami/tools/neptune
                build/last/pkg/*.deb

    include:
        # Test matrix
        - <<: *test-matrix
          env: DMD=2.074.* F=production
        - <<: *test-matrix
          env: DMD=2.074.* F=devel
        - <<: *test-matrix
          env: DMD=2.076.* F=production
        - <<: *test-matrix
          env: DMD=2.076.* F=devel

        # Package matrix
        - <<: *package-matrix
          env: DMD=2.076.* F=production
