# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Do a shallow submodule fetch
before_install: git submodule update --init

env:
    global:
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"
    matrix:
        - DMD=2.074.0-0 DIST=xenial F=devel
        - DMD=2.074.0-0 DIST=xenial F=production
        - DMD=2.076.1-0 DIST=xenial F=devel
        - DMD=2.076.1-0 DIST=xenial F=production

install: beaver dlang install

# DMD can be very memory hungry, and beaver uses make
# -j2 by default, which means 2 DMD will run in parallel, which
# can exhaust Travis VM memory. Because of this we override
# this with -j1 to make sure only one DMD is ran at a time.
script: beaver dlang make -rj1 all test
