# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Do a shallow submodule fetch
before_install: git submodule update --init

env:
    global:
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"
    matrix:
        - DMD=2.073.2-0 DIST=xenial F=devel
        - DMD=2.073.2-0 DIST=xenial F=production
        - DMD=2.074.0-0 DIST=xenial F=devel
        - DMD=2.074.0-0 DIST=xenial F=production

install: beaver dlang install

script: beaver dlang make
